name: Deploy service

on:
  push:
    branches:
      - main
    paths:
      - apps/service/**
  workflow_dispatch:

jobs:
  deploy_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image & push to ECR
        uses: kciter/aws-ecr-action@master
        with:
          path: ./apps/service
          dockerfile: ./apps/service/Dockerfile
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: dxe/helptheducks-service
          region: us-west-2
          tags: latest,${{ github.sha }}
